### ISSUE TITLE
咋用啊?

### ISSUE THREAD

**Issue by 448808614** [theGravityLab/ProjHyperai#18]

**Comment by d3ara1n** [comment]
项目不包含协议实现, 你得先有mirai或者opq(目前不支持)实装. 具体用法选择参考README中的[如何选择](https://github.com/theGravityLab/ProjHyperai#%E5%A6%82%E4%BD%95%E9%80%89%E6%8B%A9%E4%B8%80%E4%B8%AA%E5%AD%90%E9%A1%B9%E7%9B%AE%E5%B9%B6%E7%BB%A7%E7%BB%AD%E5%BC%80%E5%8F%91--how-to-begin)部分。默认就当是想要直接部署HyperaiShell(使用mirai)，这一块参考[HyperaiShell部署指南](https://projhyperai.dowob.vip/guide/2.0.about/)，然后使用插件实现功能，这一部分则同样位于指南的[插件编写部分](https://projhyperai.dowob.vip/guide/5.0.about/).
