### ISSUE TITLE
[联系方式] readme中提供的加群链接似乎存在问题

### ISSUE THREAD

**Issue by ryuujo1573** [theGravityLab/ProjHyperai#21]
好耶!
![image](https://user-images.githubusercontent.com/16525512/107687540-90571680-6ce1-11eb-834d-0d4a20ebb3bc.png)
~~群是不是凉了~~

**Comment by d3ara1n** [comment]
不好意思，被你猜到了...群凉了。考虑搞个tg群...算了。qq群都没多少人加TAT
