### ISSUE TITLE
nupkg插件包存在 PackageReference 问题

### ISSUE THREAD

**Issue by yiyungent** [theGravityLab/ProjHyperai#25]
我看到文档写，插件直接打包为 nupkg即可
但使用 `dotnet pack` 打包的nupkg，是不包含，同样为nuget引用的 `PackageReference` 的dll的，话说
大佬实现递归检索依赖了吗？已经实现nupkg解析了？

例如，   
`APlugin.nupkg`，此插件项目 `PackageReference` 引用了 `Newtonsoft.Json`，
那么 `dotnet pack` 的 `nupkg`  是不包含 `Newtonsoft.Json.dll` 的，系统内部会解析 `APlugin.nuspec` ，并且去下载 `Newtonsoft.Json.nupkg`，在解压出dll吗？

> 本人最近正在开发插件框架  [PluginCore](https://github.com/yiyungent/PluginCore)，
> 也使用了 `nupkg`  作为插件包，但不支持解析 `PackageReference`  依赖，插件作者必须手动将全部第三方包打入`nupkg`，如果大佬写了，我就参考下，谢谢

**Comment by ac682** [comment]
我记得文档里还是哪里写了，正确做法是去nuget.org把nnewtonsoft.nupkg下载下来一并丢进plugins让它自动加载依赖。依赖的依赖解析需要手动完成，注意一下自己的插件依赖了哪些库。（不过newtonjson其实自带了。

**Comment by ac682** [comment]
我一直想搞依赖解析，但怎么管理下载下来的依赖文件（.nupkg)以及在什么时机去解析依赖并安装依赖是个问题，大佬有解决方案了希望提醒一下。

**Comment by d3ara1n** [comment]
凡是plugins/*.nupkg中的对应目标平台（net5.0，自动选择兼容目标平台还没写)所包含的dll会被自动加载，Newtonsoft.Json.nupkg也是如此。依赖解析的其他问题在于下载依赖树缺失包的时机（涉及长时间io操作，不适合放在程序的主循环里，不过启动加载插件之前或许'合理'）和管理依赖（想法是放在包缓存文件夹，依赖树里有就在缓存里找，找不到就下）

算上括号里的内容那其实都不是问题，困扰自己的问题在回复他人问题的时候被解决了：）

**Comment by yiyungent** [comment]
好的，期待大佬写出依赖解析（逃，   

话说我看大佬也可以通过依赖注入服务，支持热插拔吗？还是只能跟随 主程序启动时，遍历插件.ConfigureServices 注入服务

```C#
PluginBase.ConfigureServices
```

**Comment by d3ara1n** [comment]
> 好的，期待大佬写出依赖解析（逃，
> 
> 话说我看大佬也可以通过依赖注入服务，支持热插拔吗？还是只能跟随 主程序启动时，遍历插件.ConfigureServices 注入服务
> 
> ```cs
> PluginBase.ConfigureServices
> ```

不支持，热插拔也是我所面临的问题
